// Prisma levels -- see prisma_core.js for the map legend. Every level is
// checked by tools/prisma_solve.js: solvable, and `par` is the shortest
// solution in moves. Levels 8-17 were found by tools/prisma_generate.js
// (random layouts, kept for long solutions with many pushes).
window.Lynx = window.Lynx || {};
Lynx.prismaLevels = [
  {
    name: "First light",
    hint: "Push the mirror into the beam, then drive to the exit.",
    par: 4,
    map: [
      "#######",
      "#..R..#",
      "#.....#",
      "#L....#",
      "#../..#",
      "#..S.X#",
      "#######",
    ],
    emitters: [{ at: [1, 3], dir: "E", color: "r" }],
    receivers: [{ at: [3, 1], color: "r" }],
  },
  {
    name: "Your own shadow",
    hint: "The robot blocks light. Too much colour is as bad as too little.",
    par: 7,
    map: [
      "#######",
      "#.....#",
      "#L.k.R#",
      "#.....#",
      "#.S..X#",
      "#....L#",
      "#######",
    ],
    emitters: [{ at: [1, 2], dir: "E", color: "r" }, { at: [5, 5], dir: "N", color: "b" }],
    receivers: [{ at: [5, 2], color: "r" }],
  },
  {
    name: "Turntable",
    hint: "Stepping on a round pad turns the mirrors next to it.",
    par: 6,
    map: [
      "#######",
      "#..R..#",
      "#.....#",
      "#L.\\o.#",
      "#.....#",
      "#..S.X#",
      "#######",
    ],
    emitters: [{ at: [1, 3], dir: "E", color: "g" }],
    receivers: [{ at: [3, 1], color: "g" }],
  },
  {
    name: "Weight",
    hint: "A gate opens while something stands on the plate.",
    par: 14,
    map: [
      "#######",
      "#L.D.R#",
      "#..#..#",
      "#.k#..#",
      "#._#.X#",
      "#.S#..#",
      "#######",
    ],
    emitters: [{ at: [1, 1], dir: "E", color: "b" }],
    receivers: [{ at: [5, 1], color: "b" }],
  },
  {
    name: "Magenta",
    hint: "Red and blue together make magenta.",
    par: 12,
    map: [
      "#######",
      "#L...R#",
      "#.....#",
      "#../..#",
      "#./...#",
      "#..S.X#",
      "#L#####",
    ],
    emitters: [{ at: [1, 1], dir: "E", color: "r" }, { at: [1, 6], dir: "N", color: "b" }],
    receivers: [{ at: [5, 1], color: "m" }],
  },
  {
    name: "Split decision",
    hint: "A splitter sends the beam both ways.",
    par: 16,
    map: [
      "#######",
      "#....R#",
      "#R..\\.#",
      "#L.z..#",
      "#.../.#",
      "#X.S..#",
      "#######",
    ],
    emitters: [{ at: [1, 3], dir: "E", color: "c" }],
    receivers: [{ at: [5, 1], color: "c" }, { at: [1, 2], color: "c" }],
  },
  {
    name: "Around the corner",
    hint: "Two mirrors, one wall in between.",
    par: 23,
    map: [
      "########",
      "#L.#..R#",
      "#..#...#",
      "#......#",
      "#./..\\.#",
      "#..S..X#",
      "########",
    ],
    emitters: [{ at: [1, 1], dir: "S", color: "r" }],
    receivers: [{ at: [6, 1], color: "r" }],
  },
  {
    name: "Two ways",
    hint: "The splitter feeds both receivers -- if the mirrors let it.",
    par: 19,
    map: [
      "#######",
      "##..X.#",
      "#.../.#",
      "#....\\#",
      "#/...##",
      "#..SZ.R",
      "##L#R##",
    ],
    emitters: [{ at: [2, 6], dir: "N", color: "c" }],
    receivers: [{ at: [4, 6], color: "c" }, { at: [6, 5], color: "c" }],
  },
  {
    name: "Counterweight",
    hint: "Something has to stay on the plate.",
    par: 27,
    map: [
      "#######",
      "#...X\\#",
      "#_/..##",
      "#..#\\.#",
      "#...Dk#",
      "L..S#.#",
      "#R#####",
    ],
    emitters: [{ at: [0, 5], dir: "E", color: "b" }],
    receivers: [{ at: [1, 6], color: "b" }],
  },
  {
    name: "Spin cycle",
    hint: "Turn before you push -- or push before you turn?",
    par: 27,
    map: [
      "#######",
      "#..#..L",
      "##.\\.X#",
      "#..\\..#",
      "#.o...#",
      "#..S..R",
      "#######",
    ],
    emitters: [{ at: [6, 1], dir: "W", color: "g" }],
    receivers: [{ at: [6, 5], color: "g" }],
  },
  {
    name: "Backdoor",
    par: 33,
    map: [
      "#######",
      "#.....#",
      "#..X.k#",
      "#\\/#.##",
      "L._...#",
      "R.DS.##",
      "#######",
    ],
    emitters: [{ at: [0, 4], dir: "E", color: "b" }],
    receivers: [{ at: [0, 5], color: "b" }],
  },
  {
    name: "Hall of mirrors",
    par: 32,
    map: [
      "#######",
      "#..\\..#",
      "#.../.#",
      "#X\\...#",
      "##..#/#",
      "#..S..#",
      "####LR#",
    ],
    emitters: [{ at: [4, 6], dir: "N", color: "r" }],
    receivers: [{ at: [5, 6], color: "r" }],
  },
  {
    name: "Locked light",
    par: 37,
    map: [
      "#L#R###",
      "#./.D.#",
      "#...\\.#",
      "#..\\k.#",
      "#.#k.X#",
      "#._S###",
      "#######",
    ],
    emitters: [{ at: [1, 0], dir: "S", color: "b" }],
    receivers: [{ at: [3, 0], color: "b" }],
  },
  {
    name: "Long way round",
    par: 40,
    map: [
      "#######",
      "#..##.#",
      "#.....#",
      "#X/...R",
      "#.\\.#kL",
      "#./S..#",
      "#######",
    ],
    emitters: [{ at: [6, 4], dir: "W", color: "r" }],
    receivers: [{ at: [6, 3], color: "r" }],
  },
  {
    name: "Deadlock",
    hint: "Think before every push: blocks can't be pulled.",
    par: 46,
    map: [
      "###L###",
      "#.....#",
      "#.\\/\\.#",
      "#...###",
      "##Xk..#",
      "##.S..#",
      "#####R#",
    ],
    emitters: [{ at: [3, 0], dir: "S", color: "r" }],
    receivers: [{ at: [5, 6], color: "r" }],
  },
  {
    name: "Clockwork",
    par: 49,
    map: [
      "####R##",
      "#.\\...#",
      "#./#..#",
      "#.\\.X.#",
      "#...o.#",
      "#..S.##",
      "##L####",
    ],
    emitters: [{ at: [2, 6], dir: "N", color: "g" }],
    receivers: [{ at: [4, 0], color: "g" }],
  },
  {
    name: "Labyrinth",
    hint: "The last one. Good luck.",
    par: 53,
    map: [
      "#######",
      "#.....#",
      "L.\\\\#.#",
      "##.\\..#",
      "#o.X#.#",
      "#..S..#",
      "####R##",
    ],
    emitters: [{ at: [0, 2], dir: "E", color: "g" }],
    receivers: [{ at: [4, 6], color: "g" }],
  },
];
